package com.tigerye.process.service.pipeline.mapper;

import com.tigerye.process.service.pipeline.po.ProcessLogPo;
import com.tigerye.process.service.pipeline.po.ProcessLogPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProcessLogPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_log
     *
     * @mbg.generated
     */
    long countByExample(ProcessLogPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_log
     *
     * @mbg.generated
     */
    int deleteByExample(ProcessLogPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_log
     *
     * @mbg.generated
     */
    int insertUpdate(ProcessLogPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_log
     *
     * @mbg.generated
     */
    int insertBatch(List<ProcessLogPo> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_log
     *
     * @mbg.generated
     */
    int insertUpdateBatch(List<ProcessLogPo> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_log
     *
     * @mbg.generated
     */
    int insertIgnore(ProcessLogPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_log
     *
     * @mbg.generated
     */
    int insertIgnoreBatch(List<ProcessLogPo> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_log
     *
     * @mbg.generated
     */
    int insert(ProcessLogPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_log
     *
     * @mbg.generated
     */
    int insertUpdateSelective(ProcessLogPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_log
     *
     * @mbg.generated
     */
    int insertIgnoreSelective(ProcessLogPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_log
     *
     * @mbg.generated
     */
    int insertSelective(ProcessLogPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_log
     *
     * @mbg.generated
     */
    List<ProcessLogPo> selectByExample(ProcessLogPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_log
     *
     * @mbg.generated
     */
    ProcessLogPo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ProcessLogPo record, @Param("example") ProcessLogPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ProcessLogPo record, @Param("example") ProcessLogPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProcessLogPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProcessLogPo record);
}